spring:
  main:
    banner-mode:
      'off'

  zipunzip:
    resultNameZipFile: resultFile.zip
    locale: ru

  messages:
    encoding: UTF-8

  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: db
        format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: 'classpath:homework_30/db/migrations/changeLog.xml'