insert into Country (IP, Country, Country_code, City, Currency) values ('169.238.186.7', 'Syria', 'SY', 'Mas‘adah', 'Ruble');
insert into Country (IP, Country, Country_code, City, Currency) values ('90.130.112.130', 'Indonesia', 'ID', 'Ciawi', 'Zloty');
insert into Country (IP, Country, Country_code, City, Currency) values ('249.139.232.161', 'China', 'CN', 'Hongshi', 'Real');
insert into Country (IP, Country, Country_code, City, Currency) values ('239.124.237.230', 'Peru', 'PE', 'Copa', 'Euro');
insert into Country (IP, Country, Country_code, City, Currency) values ('115.119.188.193', 'Ukraine', 'UA', 'Sartana', 'Peso');
insert into Country (IP, Country, Country_code, City, Currency) values ('191.225.154.139', 'Philippines', 'PH', 'Dagup', 'Dollar');
insert into Country (IP, Country, Country_code, City, Currency) values ('250.87.170.189', 'Azerbaijan', 'AZ', 'Şuraabad', 'Yuan Renminbi');
insert into Country (IP, Country, Country_code, City, Currency) values ('172.122.44.80', 'Philippines', 'PH', 'Libmanan', 'Ruble');
insert into Country (IP, Country, Country_code, City, Currency) values ('202.86.191.45', 'Indonesia', 'ID', 'Negara', 'Dollar');
insert into Country (IP, Country, Country_code, City, Currency) values ('179.118.100.99', 'China', 'CN', 'Leping', 'Zloty');